name: allseasons
channels:
  - conda-forge
  - defaults
  - trentoliphant
dependencies:
  - python=3.5
  - django=1.11.2
  - jinja2=2.9.6
  - mako=1.0.7
  - markupsafe=1.0
  - arrow=0.10.0
  - binaryornot=0.4.3
  - chardet=3.0.4
  - click=6.7
  - cookiecutter=1.5.1
  - decorator=4.0.11
  - pip:
    - git+https://github.com/django/django-formtools.git#egg=django-formtools[complete]
    - git+https://github.com/philippbosch/django-geoposition.git#egg=django-geoposition[complete]
    - git+https://github.com/dyve/django-bootstrap3.git#egg=django-bootstrap3[complete]
    - git+https://github.com/jazzband/django-model-utils.git#egg=django-model-utils[complete]
  - future=0.16.0
  - pip:
    - git+https://github.com/DenisCarriere/geocoder.git#egg=geocoder[complete]
  - glob2=0.5
  - jinja2-time=0.2.0
  - mock=2.0.0
  - pip:
    - git+https://github.com/vandersonmota/model_mommy.git#egg=model-mommy[complete]
    - git+https://github.com/r1chardj0n3s/parse.git#egg=parse[complete]
    - git+https://github.com/jenisys/parse_type.git#egg=parse_type[complete]
  - pbr=3.0.1
  - poyo=0.4.1
  - psycopg2=2.7.1
  - py==1.4.33
  - pip:
    - git+https://github.com/brandon-rhodes/pyephem.git#egg=pyephem[complete]
  - pytest=3.0.7
  - pip:
    - git+https://github.com/pytest-dev/pytest-bdd.git#egg=pytest-bdd=2.18.2
    - git+https://github.com/pytest-dev/pytest-splinter.git#egg=pytest-splinter[complete]
  - python-dateutil=2.6.0
  - pytz=2017.2
  - ratelim=0.1.6
  - requests=2.14.2
  - selenium=3.4.3
  - six=1.10.0
  - pip:
    - git+https://github.com/cobrateam/splinter.git#egg=splinter
  - whichcraft=0.4.1
